# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sendfile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sendfile.proto',
  package='trans_structure',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0esendfile.proto\x12\x0ftrans_structure\"\xd7\x01\n\nbksendfile\x12\r\n\x05\x66name\x18\x01 \x01(\t\x12\x1a\n\x12\x63ontrolpeople_type\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06idcard\x18\x04 \x01(\t\x12\x0b\n\x03sex\x18\x05 \x01(\t\x12\x0b\n\x03\x61ge\x18\x06 \x01(\x03\x12\r\n\x05\x66path\x18\x07 \x01(\t\x12\x0c\n\x04\x66ile\x18\x08 \x01(\x0c\x12\x15\n\rfeedbacktopic\x18\t \x01(\t\x12\r\n\x05total\x18\n \x01(\x05\x12\x11\n\tcurrentid\x18\x0b \x01(\x05\x12\x10\n\x08\x65rrornum\x18\x0c \x01(\x05\"\x96\x01\n\nbkfeedback\x12\r\n\x05\x66name\x18\x01 \x01(\t\x12\r\n\x05\x66path\x18\x02 \x01(\t\x12\x10\n\x08isfailed\x18\x03 \x01(\x05\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\r\n\x05total\x18\x05 \x01(\x05\x12\x11\n\tcurrentid\x18\x06 \x01(\x05\x12\x11\n\tbulkoknum\x18\x07 \x01(\x05\x12\x13\n\x0b\x62ulkfailnum\x18\x08 \x01(\x05\"\xa6\x01\n\nptsendfile\x12\x10\n\x08\x63\x61meraid\x18\x01 \x01(\t\x12\x13\n\x0bimportbatch\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\r\n\x05\x66name\x18\x04 \x01(\t\x12\r\n\x05\x66path\x18\x05 \x01(\t\x12\x0c\n\x04\x66ile\x18\x06 \x01(\x0c\x12\x15\n\rfeedbacktopic\x18\x07 \x01(\t\x12\r\n\x05total\x18\x08 \x01(\x05\x12\x11\n\tcurrentid\x18\t \x01(\x05\"l\n\nptfeedback\x12\r\n\x05\x66name\x18\x01 \x01(\t\x12\r\n\x05\x66path\x18\x02 \x01(\t\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x11\n\tcurrentid\x18\x04 \x01(\x05\x12\r\n\x05oknum\x18\x05 \x01(\x05\x12\x0f\n\x07\x66\x61ilnum\x18\x06 \x01(\x05\"S\n\x07sendpic\x12\x15\n\rface_filename\x18\x01 \x01(\t\x12\x0c\n\x04\x66\x61\x63\x65\x18\x02 \x01(\x0c\x12\x15\n\rback_filename\x18\x03 \x01(\t\x12\x0c\n\x04\x62\x61\x63k\x18\x04 \x01(\x0c\x62\x06proto3')
)




_BKSENDFILE = _descriptor.Descriptor(
  name='bksendfile',
  full_name='trans_structure.bksendfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fname', full_name='trans_structure.bksendfile.fname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controlpeople_type', full_name='trans_structure.bksendfile.controlpeople_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='trans_structure.bksendfile.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idcard', full_name='trans_structure.bksendfile.idcard', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sex', full_name='trans_structure.bksendfile.sex', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='trans_structure.bksendfile.age', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fpath', full_name='trans_structure.bksendfile.fpath', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='trans_structure.bksendfile.file', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feedbacktopic', full_name='trans_structure.bksendfile.feedbacktopic', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='trans_structure.bksendfile.total', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentid', full_name='trans_structure.bksendfile.currentid', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errornum', full_name='trans_structure.bksendfile.errornum', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=251,
)


_BKFEEDBACK = _descriptor.Descriptor(
  name='bkfeedback',
  full_name='trans_structure.bkfeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fname', full_name='trans_structure.bkfeedback.fname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fpath', full_name='trans_structure.bkfeedback.fpath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isfailed', full_name='trans_structure.bkfeedback.isfailed', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='trans_structure.bkfeedback.reason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='trans_structure.bkfeedback.total', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentid', full_name='trans_structure.bkfeedback.currentid', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bulkoknum', full_name='trans_structure.bkfeedback.bulkoknum', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bulkfailnum', full_name='trans_structure.bkfeedback.bulkfailnum', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=404,
)


_PTSENDFILE = _descriptor.Descriptor(
  name='ptsendfile',
  full_name='trans_structure.ptsendfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cameraid', full_name='trans_structure.ptsendfile.cameraid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='importbatch', full_name='trans_structure.ptsendfile.importbatch', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='trans_structure.ptsendfile.date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fname', full_name='trans_structure.ptsendfile.fname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fpath', full_name='trans_structure.ptsendfile.fpath', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='trans_structure.ptsendfile.file', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feedbacktopic', full_name='trans_structure.ptsendfile.feedbacktopic', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='trans_structure.ptsendfile.total', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentid', full_name='trans_structure.ptsendfile.currentid', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=573,
)


_PTFEEDBACK = _descriptor.Descriptor(
  name='ptfeedback',
  full_name='trans_structure.ptfeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fname', full_name='trans_structure.ptfeedback.fname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fpath', full_name='trans_structure.ptfeedback.fpath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='trans_structure.ptfeedback.total', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentid', full_name='trans_structure.ptfeedback.currentid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oknum', full_name='trans_structure.ptfeedback.oknum', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failnum', full_name='trans_structure.ptfeedback.failnum', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=683,
)


_SENDPIC = _descriptor.Descriptor(
  name='sendpic',
  full_name='trans_structure.sendpic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_filename', full_name='trans_structure.sendpic.face_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face', full_name='trans_structure.sendpic.face', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='back_filename', full_name='trans_structure.sendpic.back_filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='back', full_name='trans_structure.sendpic.back', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=768,
)

DESCRIPTOR.message_types_by_name['bksendfile'] = _BKSENDFILE
DESCRIPTOR.message_types_by_name['bkfeedback'] = _BKFEEDBACK
DESCRIPTOR.message_types_by_name['ptsendfile'] = _PTSENDFILE
DESCRIPTOR.message_types_by_name['ptfeedback'] = _PTFEEDBACK
DESCRIPTOR.message_types_by_name['sendpic'] = _SENDPIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

bksendfile = _reflection.GeneratedProtocolMessageType('bksendfile', (_message.Message,), dict(
  DESCRIPTOR = _BKSENDFILE,
  __module__ = 'sendfile_pb2'
  # @@protoc_insertion_point(class_scope:trans_structure.bksendfile)
  ))
_sym_db.RegisterMessage(bksendfile)

bkfeedback = _reflection.GeneratedProtocolMessageType('bkfeedback', (_message.Message,), dict(
  DESCRIPTOR = _BKFEEDBACK,
  __module__ = 'sendfile_pb2'
  # @@protoc_insertion_point(class_scope:trans_structure.bkfeedback)
  ))
_sym_db.RegisterMessage(bkfeedback)

ptsendfile = _reflection.GeneratedProtocolMessageType('ptsendfile', (_message.Message,), dict(
  DESCRIPTOR = _PTSENDFILE,
  __module__ = 'sendfile_pb2'
  # @@protoc_insertion_point(class_scope:trans_structure.ptsendfile)
  ))
_sym_db.RegisterMessage(ptsendfile)

ptfeedback = _reflection.GeneratedProtocolMessageType('ptfeedback', (_message.Message,), dict(
  DESCRIPTOR = _PTFEEDBACK,
  __module__ = 'sendfile_pb2'
  # @@protoc_insertion_point(class_scope:trans_structure.ptfeedback)
  ))
_sym_db.RegisterMessage(ptfeedback)

sendpic = _reflection.GeneratedProtocolMessageType('sendpic', (_message.Message,), dict(
  DESCRIPTOR = _SENDPIC,
  __module__ = 'sendfile_pb2'
  # @@protoc_insertion_point(class_scope:trans_structure.sendpic)
  ))
_sym_db.RegisterMessage(sendpic)


# @@protoc_insertion_point(module_scope)
